### Variables
@baseUrl = http://localhost:3000

### GET Welcome endpoint
GET {{baseUrl}}/health
Content-Type: application/json

### POST Add a new post
POST {{baseUrl}}/api/posts
Content-Type: application/json

{
  "title": "My First Post",
  "content": "This is the content of my first post.",
  "author": "Gal kosover",
  "publishDate": "2024-01-15T10:00:00.000Z"
}

### GET Get all posts
GET {{baseUrl}}/api/posts
Content-Type: application/json

### GET Get a post by ID
GET {{baseUrl}}/api/posts/6974f06f791bab619f36b2cb
Content-Type: application/json

### GET Get posts by sender
GET {{baseUrl}}/api/posts?sender=Gal kosover
Content-Type: application/json

### POST Create a new comment
POST {{baseUrl}}/api/comments
Content-Type: application/json

{
  "owner": "Gal kosover",
  "postId": "6974f06f791bab619f36b2cb",
  "content": "This is a great post!"
}

### GET Get a comment by ID
GET {{baseUrl}}/api/comments/6974f114791bab619f36b2f1
Content-Type: application/json

### GET Get all comments for a specific post
GET {{baseUrl}}/api/comments/post/6974f06f791bab619f36b2cb
Content-Type: application/json

### PUT Update a comment
PUT {{baseUrl}}/api/comments/6974f114791bab619f36b2f1
Content-Type: application/json

{
  "content": "Updated comment content"
}

### DELETE Delete a comment
DELETE {{baseUrl}}/api/comments/6974f114791bab619f36b2f1
Content-Type: application/json